using LocalVoice;
int count=0;
void Check(bool value,string why){if(!value)throw new Exception(why);count++;}
var transcript=new Transcript{Captions=new(){new(){Speaker="Speaker 1",Text="First",Start=0,End=1,Embedding=new[]{1d,0d}},new(){Speaker="Speaker 1",Text="Wrong identity",Start=1,End=2,Embedding=new[]{0d,1d}},new(){Speaker="Speaker 2",Text="Second",Start=2,End=3,Embedding=new[]{0d,1d}},new(){Speaker="Speaker 1",Text="Similar to second",Start=3,End=4,Embedding=new[]{.01,1d}}}};
transcript.NameFirst(transcript.Captions[0].Id,"Seb");Check(transcript.Name(transcript.Captions[1].Speaker)=="Seb","First naming updates all identity labels");
transcript.NameFirst(transcript.Captions[2].Id,"John");transcript.Correct(transcript.Captions[1].Id,"Speaker 2");Check(transcript.Name(transcript.Captions[0].Speaker)=="Seb","Correction preserves other named speaker");Check(transcript.Captions[1].Confirmed,"Correction becomes protected");Check(transcript.Captions[3].Speaker=="Speaker 2","Confirmed examples reclassify clear matches");Check(transcript.Export("txt").Contains("John: Wrong identity"),"Exports honor corrected identity");transcript.Undo();Check(!transcript.Captions[1].Confirmed,"Undo removes manual confirmation");
var precision=new Transcript{SpeakerModel="precision",Captions=new(){new(){Speaker="A",Confirmed=true,Embedding=new[]{1d,0d}},new(){Speaker="B",Confirmed=true,Embedding=new[]{0d,1d}},new(){Speaker="B",Embedding=new[]{.85,Math.Sqrt(1-.85*.85)}}}};
precision.Learn();Check(precision.Captions[2].Speaker=="B","Precision pack uses its conservative calibrated threshold");precision.SpeakerModel="accurate";precision.Learn();Check(precision.Captions[2].Speaker=="A","Legacy pack retains its own threshold");
var export=new Transcript{Captions=new(){new(){Text="<hello> & world -->",Start=1.234,End=2.5,Speaker="Speaker 1"}},Names=new(){["Speaker 1"]="Seb"}};
Check(export.Export("srt").Contains("00:00:01,234 --> 00:00:02,500"),"Accurate millisecond captions");Check(export.Export("vtt").StartsWith("WEBVTT\n\n"),"WebVTT header");Check(export.Export("srt").Contains("Seb: &lt;hello&gt; &amp; world →"),"Caption output escapes markup");
Check(Transcript.Cosine(new[]{0d,0d},new[]{1d,0d})==null,"Zero vector rejected");Check(Transcript.Cosine(new[]{double.NaN},new[]{1d})==null,"NaN vector rejected");Check(ReadDocument.Plain("## Summary\n**Hello** [friend](https://example.com)")=="Summary\nHello friend","Markdown cleaned for reading");Check(ReadDocument.Sentences("One. Two!\nThree").Length==3,"Sentence seek boundaries");Check(ReadDocument.Sentences(new string('a',2500)).All(x=>x.Length<=1200),"Bounded synthesis requests");
var temp=Path.Combine(Path.GetTempPath(),"voice-prefs-"+Guid.NewGuid(),"prefs.json");try{var prefs=new Preferences{DictationModel="whisper-tiny",TranscriptionModel="whisper-large-turbo",DictationDevice="cpu",TranscriptionDevice="gpu",SpeakerModel="precision"};prefs.Save(temp);var read=Preferences.Load(temp);Check(read.DictationDevice=="cpu"&&read.TranscriptionDevice=="gpu","Independent acceleration persisted");Check(read.TranscriptionModel=="whisper-large-turbo"&&read.SpeakerModel=="precision","Model selections persisted");read.PreferredGpu="GPU-aaaa";read.Save(temp);Check(Preferences.Load(temp).PreferredGpu=="GPU-aaaa","GPU selection persists by stable identity");File.WriteAllText(temp,"{\"DictationDevice\":\"gpu\",\"TranscriptionDevice\":\"gpu\"}");var migrated=Preferences.Load(temp);Check(migrated.DictationDevice=="auto"&&migrated.TranscriptionDevice=="auto","Legacy acceleration preferences migrate to GPU-first fallback");read.Rate=5;read.Save(temp);Check(Preferences.Load(temp).Rate==2,"Invalid rate clamped");File.WriteAllText(temp,"{\"DictationDevice\":\"cloud\"}");bool rejected=false;try{Preferences.Load(temp);}catch(InvalidDataException){rejected=true;}Check(rejected,"Invalid device rejected");}finally{Directory.Delete(Path.GetDirectoryName(temp)!,true);}
Console.WriteLine($"WINDOWS_DOMAIN_OK {count} assertions");
