import assert from 'node:assert/strict';
import {spawnSync,spawn} from 'node:child_process';
import {access,readdir,mkdtemp,rm,readFile,writeFile,realpath} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import readline from 'node:readline';
import { resampleAudio } from '../../core/audio.mjs';
const app=path.resolve('release/native/DAVE.app'), resources=path.join(app,'Contents/Resources');
const run=(bin,args)=>{const r=spawnSync(bin,args,{encoding:'utf8',timeout:30000});assert.equal(r.status,0,r.stderr||String(r.error));return r.stdout;};
run('codesign',['--verify','--deep','--strict',app]);
const exe=path.join(app,'Contents/MacOS/DAVE');
const diagnostic=JSON.parse(run(exe,['--diagnose']));
assert.equal(diagnostic.bundle,'local.localvoice.mac');assert.equal(diagnostic.name,'DAVE');assert.equal(diagnostic.native,true);assert.equal(diagnostic.runtime,true);assert.equal(diagnostic.backend,true);assert.ok(diagnostic.sentences>=2);
assert.doesNotMatch(run('otool',['-L',exe]),/Electron|WebKit|Chromium/);
for(const name of ['electron','playwright','electron-builder']) await assert.rejects(access(path.join(resources,'backend/node_modules',name)));
const session=await realpath(await mkdtemp(path.join(os.tmpdir(),'native-package-test-')));
const child=spawn(path.join(resources,'runtime/node'),[path.join(resources,'backend/service.mjs')],{env:{...process.env,LOCALVOICE_MODELS:path.resolve('.cache/models'),LOCALVOICE_SESSION:session}});
let i=0;const pending=new Map();let errors='';child.stderr.on('data',b=>errors+=b);
readline.createInterface({input:child.stdout}).on('line',line=>{const r=JSON.parse(line),p=pending.get(r.id);if(p){pending.delete(r.id);r.error?p.reject(new Error(r.error)):p.resolve(r.result);}});
child.on('exit',code=>{for(const p of pending.values())p.reject(new Error('Bundled runtime exited '+code+errors));pending.clear();});
const request=(command,args={})=>new Promise((resolve,reject)=>{const id=String(++i);pending.set(id,{resolve,reject});child.stdin.write(JSON.stringify({id,command,...args})+'\n');});
const timeout=setTimeout(()=>child.kill(),120000);
try {
 const models=await request('list');assert.ok(models.find(x=>x.id==='kokoro-q8'&&x.installed));
 const audio=await request('synthesize',{model:'kokoro-q8',text:'Native reading on this Mac.',voice:'af_heart'});
 assert.ok((await readFile(audio.path)).length>24000);
 const fixed = await readFile('macos/Tests/Fixtures/speech.wav');
 assert.equal(fixed.readUInt16LE(20),1); assert.equal(fixed.readUInt16LE(22),1); assert.equal(fixed.readUInt16LE(34),16);
 const samples = Float32Array.from({length:(fixed.length-44)/2}, (_,i)=>fixed.readInt16LE(44+i*2)/32768);
 const pcm = resampleAudio(samples,fixed.readUInt32LE(24));
 const pcmPath = path.join(session,'fixture.f32'); await writeFile(pcmPath,Buffer.from(pcm.buffer));
 assert.equal((await request('diarization-status')).installed,true,'Install test speaker pack first');
 const captions = await request('transcribe-chunk',{model:'whisper-tiny',path:pcmPath,jobID:'package-check',separateSpeakers:true,expectedSpeakers:0});
 assert.ok(captions.segments.length); assert.ok(captions.segments.some(s=>s.speaker==='Speaker 1'));
 const text = captions.segments.map(s=>s.text).join(' ').toLowerCase();
 assert.match(text,/garden/); assert.match(text,/kitchen/);
 await request('reset-transcription',{jobID:'package-check'});
 console.log(JSON.stringify(diagnostic));console.log('NATIVE_PACKAGE_OK');
}finally{clearTimeout(timeout);child.kill();await rm(session,{recursive:true,force:true});}
