using System.Collections.Concurrent;
using System.Diagnostics;
using System.Text;
using System.Text.Json;
namespace LocalVoice;
public sealed class Backend:IDisposable {
 readonly string session; readonly ConcurrentDictionary<string,TaskCompletionSource<JsonElement>> pending=new();readonly SemaphoreSlim writer=new(1,1);Process? process;bool disposed;
 public Backend(){session=Path.Combine(Preferences.DirectoryPath,"sessions",Guid.NewGuid().ToString());}
 public string Session=>session;
 void Start(){if(disposed)throw new ObjectDisposedException(nameof(Backend));if(process is{HasExited:false})return;
  Directory.CreateDirectory(session);var home=AppContext.BaseDirectory;var start=new ProcessStartInfo(Path.Combine(home,"runtime","node.exe")){UseShellExecute=false,CreateNoWindow=true,RedirectStandardInput=true,RedirectStandardOutput=true,RedirectStandardError=true,StandardOutputEncoding=Encoding.UTF8,StandardErrorEncoding=Encoding.UTF8};start.ArgumentList.Add(Path.Combine(home,"backend","service.mjs"));start.Environment["LOCALVOICE_SESSION"]=session;start.Environment["TEMP"]=session;start.Environment["TMP"]=session;start.Environment["LOCALVOICE_MODELS"]=Path.Combine(Preferences.DirectoryPath,"models");start.Environment["LOCALVOICE_WHISPER_BIN"]=Path.Combine(home,"runtime","cuda","whisper-cli.exe");start.Environment["LOCALVOICE_WHISPER_CPU_BIN"]=Path.Combine(home,"runtime","cpu","whisper-cli.exe");
  var p=new Process{StartInfo=start,EnableRaisingEvents=true};p.Exited+=(_,_)=>{if(ReferenceEquals(process,p))Fail(new IOException("Speech service stopped. Retry the operation; your text is preserved."));};p.OutputDataReceived+=(_,e)=>{if(e.Data==null)return;try{using var doc=JsonDocument.Parse(e.Data);var r=doc.RootElement;if(r.TryGetProperty("id",out var id)&&id.ValueKind==JsonValueKind.String&&pending.TryRemove(id.GetString()!,out var task)){if(r.TryGetProperty("error",out var error))task.TrySetException(new IOException(error.GetString()));else task.TrySetResult(r.GetProperty("result").Clone());}}catch(Exception ex){Fail(new IOException("Invalid response from the speech service.",ex));}};
  p.ErrorDataReceived+=(_,e)=>{if(e.Data!=null)Debug.WriteLine(e.Data);};process=p;if(!p.Start())throw new IOException("Could not start the local speech service.");p.BeginOutputReadLine();p.BeginErrorReadLine();
 }
 void Fail(Exception ex){foreach(var key in pending.Keys)if(pending.TryRemove(key,out var t))t.TrySetException(ex);}
 public async Task<JsonElement> Request(string command,object? values=null,CancellationToken token=default){token.ThrowIfCancellationRequested();Start();var id=Guid.NewGuid().ToString();var fields=values==null?new Dictionary<string,object?>():JsonSerializer.Deserialize<Dictionary<string,object?>>(JsonSerializer.Serialize(values))!;fields["id"]=id;fields["command"]=command;var json=JsonSerializer.Serialize(fields);if(Encoding.UTF8.GetByteCount(json)>64000)throw new ArgumentException("Text is too long for one request.");var completion=new TaskCompletionSource<JsonElement>(TaskCreationOptions.RunContinuationsAsynchronously);pending[id]=completion;using var registration=token.Register(()=>{Cancel();completion.TrySetCanceled(token);});try{await writer.WaitAsync(token);try{await process!.StandardInput.WriteLineAsync(json);await process.StandardInput.FlushAsync();}finally{writer.Release();}return await completion.Task;}finally{pending.TryRemove(id,out _);}}
 public async Task<string> WriteAudio(float[] samples,CancellationToken token){Directory.CreateDirectory(session);var path=Path.Combine(session,Guid.NewGuid()+".f32");byte[] bytes=new byte[samples.Length*4];Buffer.BlockCopy(samples,0,bytes,0,bytes.Length);await File.WriteAllBytesAsync(path,bytes,token);return path;}
 public void Cancel(){var p=process;process=null;if(p!=null){try{if(!p.HasExited)p.Kill(entireProcessTree:true);}catch(InvalidOperationException){}finally{p.Dispose();}}Fail(new OperationCanceledException("Speech operation canceled."));}
 public void Dispose(){if(disposed)return;disposed=true;Cancel();try{Directory.Delete(session,true);}catch(IOException){}catch(UnauthorizedAccessException){}}
}
